### ISSUE TITLE
Django issue

### ISSUE THREAD

**Issue by Srivastava-Sudhanshu** [Srivastava-Sudhanshu/My_Web_App#1]
getting error while updating record
![image](https://user-images.githubusercontent.com/96864288/154320955-5bca7b10-9baa-480a-88dd-dff256f8c025.png)
editstudent.html
<img width="960" alt="Screenshot 2022-02-16 230301" src="https://user-images.githubusercontent.com/96864288/154322910-f2af3662-dab4-40f4-a02f-296a85373134.png">

views.py
<img width="960" alt="Screenshot 2022-02-16 230207" src="https://user-images.githubusercontent.com/96864288/154322926-06be53fc-7af1-4749-a880-410edc4e40f2.png">\

urls.py
![image](https://user-images.githubusercontent.com/96864288/154323011-afeda84d-6af6-4084-b870-4470fde1340c.png)
 
from here I am redirecting to the update screen
![image](https://user-images.githubusercontent.com/96864288/154323180-e831c4ee-23f7-4f8b-9994-fcb41b4e9d02.png)

this is my update screen
<img width="960" alt="image" src="https://user-images.githubusercontent.com/96864288/154323628-6c9e021d-0bbd-454e-b72e-406ead9cba47.png">

**Comment by MDFARHYN** [comment]
you are not using any url redirect in your update view. You need to be add url redirect somethings like that `return redirect('your redirect url') `

**Comment by Srivastava-Sudhanshu** [comment]
> 

Thanks @MDFARHYN  for your valuable response.
I have attached my views.py snapshot can u plz look it once and tell where am I making mistake.

**Comment by Srivastava-Sudhanshu** [comment]
Please help me out

**Comment by Srivastava-Sudhanshu** [comment]
I found the solution.. Thanks
